name: Deploy de produção

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: debian-latest

    steps:
      - name: Checando codigo
        uses: actions/checkout@v4
      
      - name: Setup note.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Instalando dependencias backend
        working-directory: ./back
        run: npm install

      - name: Instalando dependencias frontend
        working-directory:: ./front
        run: npm run build
      
      - name: Deploy no servidor
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/cardapioNFC
            git pull origin main
            cd back
            npm install --production
            pm2 restart ecosystem.config.js
            cd ..front
            rm -rf /var/www/frontend/*
            rm -rf dist/*
            cp -r dist/* /var/www/frontend/
            sudo systemctl reload nginx