name: Deploy de produção

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checando codigo
        uses: actions/checkout@v4
      
      - name: Setup note.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Instalando dependencias backend
        run: npm install
        working-directory: ./back
        
      - name: Instalando dependencias frontend
        run: |
          npm install
          npm run build
        working-directory: ./front
      
      - name: Deploy no servidor
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/cardapioNFC
            git pull origin main
            cd back
            npm install --production
            pm2 restart ecosystem.config.js
            cd ../front
            sudo rm -rf /var/www/frontend/*
            sudo cp -r dist/* /var/www/frontend/
            sudo chown -R www-data:www-data /var/www/frontend
            sudo systemctl reload nginx